### PR TITLE
Adding support for nextCursor

### LINKED ISSUE #6: Support for nextCursor
## The Issue
When you request orders on Walmart's Orders API using the [/v3/orders](https://developer.walmart.com/api/us/mp/orders#operation/getAllOrders) endpoint they return a `nextCursor` property in the `meta` response. Here's a sample of the `nextCursor`:
```
?limit=10
&hasMoreElements=true
&soIndex=18
&poIndex=10
&partnerId=10005555555
&sellerId=105555555
&createdStartDate=2023-07-17T00:00:00-06:00
&createdEndDate=2023-07-19T23:04:58.242Z
&shipNodeType=SellerFulfilled
```

They want you to use that for the querystring parameters of your next call to get the next page. 
The `Walmart\Apis\MP\US\OrdersApi::getAllOrders()` method needs some way to support requesting that next page of orders.

It looks like this is not the only endpoint that uses the `nextCursor` meta property to support pagination.

I'd be happy to create a PR for this, but first I'd like to:
1. Confirm an acceptable solution with @jlevers 
2. Make sure what's implemented allows regeneration of the API classes using the open api generator (assuming that's a goal of this project)

## Possible solution
Take a `nextCursor` argument on the `getAllOrders` method and ignore all other arguments. Just use the nextCursor as the query string for the API Call if the nextCursor is not null.

### PR DESCRIPTION
**Pull request by friendscottn**
Fixes #6 

I tried the following approaches before settling on a fix:
 - **Adding an additional parameter** `nextCursor` to the api spec. This wasn't the greatest solution though because you end up needing to figure out how to customize the `src/Apis/MP/US/OrdersApi.php::getAllOrdersRequest` function to add special case handling for the `nextCursor` parameter and not send the other default parameters. It seems like avoiding special cases like this is better if you can when working on generated code like this.
 - **Adding a new pseudo endpoint** with a path parameter containing the full `nextCursor` querystring `v3/orders/{nextCursor}`. This was no good because you can't include special characters (?, &, etc) in a path parameter according to the [openapi specs](https://swagger.io/specification/#parameterObject) I was looking through.

I settled on a solution where I **add the additional missing query string parameters** contained within the `nextCursor` response to the existing `/v3/orders` endpoint. 

This is a little annoying for the end user of this library because you need to break up the querystring formatted `nextCursor` that you receive and then feed it back into the same `getAllOrders()` to get the subsequent pages. It might be useful to include a helper or utility class in this library to make this easy for people. But this seems like a nice to have not really necessary.

One thing I don't love about this solution is that i had to set **all** of the parameters for the `v3/orders` endpoint in the [schema-customizations.json](https://github.com/friendscottn/walmart-api-php/blob/main/resources/schema-corrections.json). Ideally I could just set the additional missing parameters and these would get merged with the others for this particular problem. It might be a good idea to add `resources/scehema-additions.json` that uses `array_merge_recursive` under the hood to add to the schemas during schema customization. Just a thought though. This seems good enough to me for now

### CODE REVIEW

**Comment by jlevers** [comment]
Thanks for this @friendscottn – I'm going to take a proper look at it next week.

**Comment by jlevers** [comment]
Hey @friendscottn – sorry for the delay here.

This looks good, but I'd like to get the recursive schema merging solution you mentioned figured out before I merge this, because the schema corrections file is going to get messy fast without it.

I think the simplest solution here is to make `array_merge_recursive_distinct` check each array being merged for a `__mode` key, which can be set to `append` or `overwrite` (with `overwrite` as the default, if the `__mode` key isn't present). How does that sound to you?

**Comment by friendscottn** [comment]
Hey @jlevers, Yeah getting the merge option working first seems like a good idea.
Your `__mode` solution sounds great to me.

**Comment by jlevers** [comment]
Just realized there was an implicit ask in my response that may have been unclear. Are you down to implement support for the `__mode` key?

**Comment by friendscottn** [comment]
Oh yeah np. 
So starting on this it seems like the `__mode` key is not allowed on json arrays directly.
```json
{
  "parameters": [
    "__mode": "append",
    {
      "name": "hasMoreElements",
      "in": "query",
      "description": "hasMoreElements",
      "required": false,
      "schema": {
        "type": "string"
      }
    }
  ]
}
```

Didn't think about that. We'd either have to move the `__mode` to an object (which feels kinda awkward):
```json
{
  "parameters": [
    {
      "__mode": "append"
    },
    {
      "name": "hasMoreElements",
      "in": "query",
      "description": "hasMoreElements",
      "required": false,
      "schema": {
        "type": "string"
      }
    }
  ]
}
```

I'm feeling like the `schema_additions.json` file feels a little better. What do you think?

**Comment by friendscottn** [comment]
Mwahh haha! You're too late @jlevers the schema-additions.json has been added!

**Review by jlevers — APPROVED** [review]
Ah, good point about the issue of not being able to put the `__mode` key in the right place – your solution of the `schema-additions.json` file works for me! Thanks Scott :)

**Pull request merged**
